name: Deploy Project
on: [push,workflow_dispatch]
jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Install Node js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run test cases
        run: npm test
  deploy:
    needs: install-node
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        uses:
          peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
